### ISSUE TITLE
`xfer -u` does not properly manage folders

### ISSUE THREAD

**Issue by rgiot** [M4Duke/cpcxfer#4]
Let say we use the following kind of arguments :

```
xfer -u ipaddr file path opt		- Upload file, opt 0: no header add, 1: add ascii header
```
if file is a directory, `xfer` ends by saying there are no errors  while the CPC receives a file (seems to be empty) of the name of the folder.

The expected behavior behavior should be:
 - raising of an error because file is a directory and not a file
 - deep copy of everything inside the folder to the cpc sd ( 👍  for this behavior)

Current behavior on PC side
```
$ file DSK
DSK: directory
$ ../cpcxfer/xfer -u 192.168.1.27 ./DSK /
Upload OK! # BUT failded in fact
```

Current behavor on CPC side
```
CAT
...
DSK     .        1K
...
```

Expected behavior on PC side
```
$ file DSK
DSK: directory
$ ../cpcxfer/xfer -u 192.168.1.27 ./DSK /
Upload OK! # but it is a real success
```

Expected behavor on CPC side
```
CAT
...
>DSK     
```

**Comment by M4Duke** [comment]
That must be a Linux issue

In main.c when opening the file for upload it does:
fd = fopen(filename, "rb");
	if ( fd == NULL )
	{	printf("file %s not found\n", filename);
		return;
}

On windows it will not open a directory with fopen. I guess a filesize check should be added aswell since linux would open a directory if specified and not return null.

**Comment by M4Duke** [comment]
A quick fix would be:
fseek(fd, 0, SEEK_END);
if ( ftell(fd) < 0 )
{ 	printf("file %s not found\n", filename);
        fclose(fd);
        return;
}
fseek(fd, 0, SEEK_SET);

That should work for linux too. Will test sometime and commit fix, unless you do it first ;)
